<?php
    require_once("config.php");

    function base64url_encode($data) {
        return rtrim(strtr(base64_encode($data), '+/', '-_'), '='); // para evitar espacios o caracteres a la derecha
    }

    class AuthHelper {
        function getAuthHeaders() { //hago llegar la autorizacion
            $header = "";
            if(isset($_SERVER['HTTP_AUTHORIZATION']))
                $header = $_SERVER['HTTP_AUTHORIZATION'];
            if(isset($_SERVER['REDIRECT_HTTP_AUTHORIZATION']))
                $header = $_SERVER['REDIRECT_HTTP_AUTHORIZATION'];
            return $header;
        }

        function createToken($payload) { //creo el token
            $header = array(
                'alg' => 'HS256',
                'typ' => 'JWT'
            );
            
            $payload['exp'] = time() + JWT_EXP; //valor a exprirar

            $header = base64url_encode(json_encode($header));//primero lo hago json para despues pasarlo a base64
            $payload = base64url_encode(json_encode($payload));
            
            $signature = hash_hmac('SHA256', "$header.$payload", JWT_KEY, true);
            $signature = base64url_encode($signature);

            $token = "$header.$payload.$signature"; // creo el token
            
            return $token;
        }

        function verify($token) {  // verifico si existe ese token comparando firmas
            // $header.$payload.$signature

            $token = explode(".", $token); // [$header, $payload, $signature]
            $header = $token[0];
            $payload = $token[1];
            $signature = $token[2];

            $new_signature = hash_hmac('SHA256', "$header.$payload", JWT_KEY, true);
            $new_signature = base64url_encode($new_signature);

            if($signature!=$new_signature) { //comparo firmas
                return false;
            }

            $payload = json_decode(base64_decode($payload));

            if($payload->exp<time()) { //si expiro el token
                return false;
            }

            return $payload;
        }

        function currentUser() {
            $auth = $this->getAuthHeaders(); // "Bearer $token" 
            $auth = explode(" ", $auth); // ["Bearer", "$token"]

            if($auth[0] != "Bearer") {
                return false;
            }

            return $this->verify($auth[1]); // Si está bien nos devuelve el payload
        }
    }
